### PR TITLE
policies: fix lookup unexisting value

### PR DESCRIPTION
**Pull request by MarinPostma**
This pr fixes a bug in the policies variable resolver that would return None on a lookup for an unexisting value in a header.

This is not a _very robust_ fix though. A more robust fix would differentiate between static properties and computed properties. We should aim a better compat with js.

### CODE REVIEW

**Comment by penberg** [comment]
@MarinPostma A small test case to at least trigger the failure?

**Comment by CodingDoug** [comment]
Another way to handle missing data (or anything unexpected) is to immediately deny the operation.  This would help prevent security surprises.

I believe I had also noticed that, for onRead operations, it's possible to put a null value inside an entity field (an invalid value) that came from a missing header lookup.  This sounds like bad behavior - I would have preferred that the operation simply fail with a meaningful error message in the output.

**Comment by MarinPostma** [comment]
@CodingDoug that's not a good idea: it's not expected behavior, and would bite you back. Here's an example:
```typescript
(entity, context) => {
    if (context.headers["somefield"]) { // <- this would blow up!
        if (context.headers["someField"] == 42) {
            return Action.Allow;
        }
    }
}
```

**Comment by CodingDoug** [comment]
As

> @CodingDoug that's not a good idea: it's not expected behavior, and would bite you back. Here's an example:
> 
> ```ts
> (entity, context) => {
>     if (context.headers["somefield"]) { // <- this would blow up!
>         if (context.headers["someField"] == 42) {
>             return Action.Allow;
>         }
>     }
> }
> ```

As it stands now with Record<string, string>, yes, that would be a problem.  But if we had a data structure contain the headers that exposes a check for existence (that doesn't ever fail), that would be fine. That way, they are specifically opting into optionality of the header with clear code.

**Review by penberg — APPROVED** [review]

**Pull request merged**
